Addition of ESP32 board
libretuya/esphome-kickstart pull request #9
Opened 2023-12-14 15:22 UTC by yeyeto2788

Add ESP32 board and fix pin naming and addition of function of pin in select options.

2023-12-14 17:02 UTC, kuba2k2 requested changes

2023-12-14 17:02 UTC, kuba2k2 commented on components/pinscan/pinscan.cpp
> +    D10, // GPIO1
These pinouts will only work for NodeMCU (which uses these strange D# mappings). It would be more universal to order the GPIO by number and don't bother naming them with D#. Instead of macros you can simply put the GPIO number as an integer.

2023-12-14 17:02 UTC, kuba2k2 commented on yaml/import-esp8266.yaml
> +  board: nodemcuv2
I'd prefer to use a more generic board, since no actual IoT devices will ever contain a NodeMCU. Same goes for ESP32.

2023-12-14 17:02 UTC, kuba2k2 commented on components/pinscan/pinscan.cpp
> +    T0,     // GPIO4
What are the T# pins and where are they defined? Just like on esp8266, you can simply use numeric values here, and describe pin functionality in the comment (and in YAML).

2023-12-14 17:32 UTC, Cossid commented on yaml/import-esp8266.yaml
> +  board: nodemcuv2
Expanding on this, the general considered defaults are
esp8266: `esp01_1m` - https://docs.platformio.org/en/latest/boards/espressif8266/esp01_1m.html
esp32: `esp32dev` - https://docs.platformio.org/en/latest/boards/espressif32/esp32dev.html

2023-12-15 07:58 UTC, yeyeto2788 commented
@kuba2k2, @Cossid changes added. Please review and if there is anything else I can do just let me know.

2023-12-15 08:51 UTC, kuba2k2 commented
Yes, I think everyone would prefer if the ESP8266 pins were ordered numerically, now they aren't.
Also, there are a few pins missing on ESP32 - 1, 3, 16, 17, 34, 35, 36, 39 etc. Pin GPIO13 has a typo and says 14.

2023-12-15 11:21 UTC, yeyeto2788 commented
Done 🕺🏽

2023-12-15 11:42 UTC, kuba2k2 approved these changes

2023-12-15 12:57 UTC, merged